apiVersion: apps/v1
kind: Deployment

metadata:
  name: ai-devops-oncall-agent
  labels:
    app: ai-devops-oncall-agent

spec:
  replicas: 1
  selector:
    matchLabels:
      app: ai-devops-oncall-agent

  template:
    metadata:
      labels:
        app: ai-devops-oncall-agent

    spec:
      containers:
        - name: ai-devops-oncall-agent
          image: prabhatcr001.azurecr.io/ai-devops-oncall-agent:b7b752b7f4e5dd8a1fd5f464aeb6a799809a643f
          imagePullPolicy: Always

          ports:
            - containerPort: 8000