apiVersion: apps/v1
kind: Deployment

metadata:
  name: ai-devops-oncall-agent
  namespace: ai-devops
  labels:
    app: ai-devops-oncall-agent

spec:
  replicas: 1

  selector:
    matchLabels:
      app: ai-devops-oncall-agent

  template:
    metadata:
      labels:
        app: ai-devops-oncall-agent

    spec:
      containers:
        - name: ai-devops-oncall-agent
          image: prabhatcr001.azurecr.io/ai-devops-oncall-agent:latest
          imagePullPolicy: Always

          ports:
            - containerPort: 8000