apiVersion: apps/v1
kind: Deployment
metadata:
  name: ai-devops-oncall-agent
  labels:
    app: ai-devops-oncall-agent

spec:
  replicas: 1

  selector:
    matchLabels:
      app: ai-devops-oncall-agent

  template:
    metadata:
      labels:
        app: ai-devops-oncall-agent

    spec:
      serviceAccountName: ai-devops-oncall-agent

      containers:
        - name: ai-devops-oncall-agent
          image: prabhatcr001.azurecr.io/ai-devops-oncall-agent:00269724f9ff4b1b74ad8a77966ed8a546398fe4
          imagePullPolicy: Always

          ports:
            - containerPort: 8000

          envFrom:
            - configMapRef:
                name: ai-devops-oncall-agent-config

            - secretRef:
                name: ai-devops-oncall-agent-secret